version: '3'
services:
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_dbms_security_auth_enabled=true
    container_name: neo4j-weak